---
title: "Tempered stable report"
author: "Shu Wei"
date: ""
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,fig.width=7, fig.height=7)
```

## Tempered stable (independent case) Report

```{r, echo=FALSE}
library(car)
library(forecast)
library(moments)
```

Loading simulation results:
  
```{r}
load("./results/TSD_simulation_0_1_T500.Rdata")
resultsA1T1<-results
load("./results/TSD_simulation_0_1_T1000.Rdata")
resultsA1T2<-results
load("./results/TSD_simulation_0_1_T1500.Rdata")
resultsA1T3<-results

load("./results/TSD_simulation_0_4_T500.Rdata")
resultsA2T1<-results
load("./results/TSD_simulation_0_4_T1000.Rdata")
resultsA2T2<-results
load("./results/TSD_simulation_0_4_T1500.Rdata")
resultsA2T3<-results

load("./results/TSD_simulation_0_7_T500.Rdata")
resultsA3T1<-results
load("./results/TSD_simulation_0_7_T1000.Rdata")
resultsA3T2<-results
load("./results/TSD_simulation_0_7_T1500.Rdata")
resultsA3T3<-results

parametrosA1<-c(0.1,0.8,1)
parametrosA2<-c(0.4,0.5,1.5)
parametrosA3<-c(0.7,1,0.5)
```

Functions:
  
```{r}
mean.sd<-function(y){
  tabla<-as.matrix(c(mean(y),sd(y)))
  rownames(tabla)<-c("mean","sd")
  return(tabla)
}
kurtosis.skewness<-function(y){
  tabla<-as.matrix(c(kurtosis(y),skewness(y)))
  return(tabla)
}
```


## Scenario 1

$\alpha=0.1$,\
$\lambda_+=0.8$,\
$\lambda_-=1$,\

### Simulation with my codes

```{r}
tablaA1T1<-apply(resultsA1T1,2,mean.sd)
tablaA1T2<-apply(resultsA1T2,2,mean.sd)
tablaA1T3<-apply(resultsA1T3,2,mean.sd)
tablaA1<-rbind(tablaA1T1,tablaA1T2,tablaA1T3)
row.names(tablaA1)<-c("T1.mean","sd","T2.mean","sd","T3mean","sd")
round(tablaA1,4)
parametrosA1
```


```{r}
tablaA1T1<-apply(resultsA1T1,2,kurtosis.skewness)
tablaA1T2<-apply(resultsA1T2,2,kurtosis.skewness)
tablaA1T3<-apply(resultsA1T3,2,kurtosis.skewness)
rownames(tablaA1T1)<-c("kurtosis","skewness")
rownames(tablaA1T2)<-c("kurtosis","skewness")
rownames(tablaA1T3)<-c("kurtosis","skewness")
tablaA1<-rbind(tablaA1T1,tablaA1T2,tablaA1T3)
round(tablaA1,4)
```

Density estimates 

```{r,fig.width=10, fig.height=3}
par(mfrow=c(1,3))
plot(density(resultsA1T1[,1],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(theta[0]),main="", cex.lab = 1.5)
points(density(resultsA1T2[,1],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA1T3[,1],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA1[1],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))

plot(density(resultsA1T1[,2],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(theta[1]),main="", cex.lab = 1.5)
points(density(resultsA1T2[,2],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA1T3[,2],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA1[2],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))

plot(density(resultsA1T1[,3],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(gamma),main="", cex.lab = 1.5)
points(density(resultsA1T2[,3],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA1T3[,3],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA1[3],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))
```


## Scenario 2

$\alpha=0.4$,\
$\lambda_+=0.5$,\
$\lambda_-=1.5$,\

### Simulation with my codes

```{r}
tablaA2T1<-apply(resultsA2T1,2,mean.sd)
tablaA2T2<-apply(resultsA2T2,2,mean.sd)
tablaA2T3<-apply(resultsA2T3,2,mean.sd)
tablaA2<-rbind(tablaA2T1,tablaA2T2,tablaA2T3)
row.names(tablaA2)<-c("T1.mean","sd","T2.mean","sd","T3mean","sd")
round(tablaA2,4)
parametrosA2
```


```{r}
tablaA2T1<-apply(resultsA2T1,2,kurtosis.skewness)
tablaA2T2<-apply(resultsA2T2,2,kurtosis.skewness)
tablaA2T3<-apply(resultsA2T3,2,kurtosis.skewness)
rownames(tablaA2T1)<-c("kurtosis","skewness")
rownames(tablaA2T2)<-c("kurtosis","skewness")
rownames(tablaA2T3)<-c("kurtosis","skewness")
tablaA2<-rbind(tablaA2T1,tablaA2T2,tablaA2T3)
round(tablaA2,4)
```

Density estimates 

```{r,fig.width=10, fig.height=3}
par(mfrow=c(1,3))
plot(density(resultsA2T1[,1],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(theta[0]),main="", cex.lab = 1.5)
points(density(resultsA2T2[,1],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA2T3[,1],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA2[1],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))

plot(density(resultsA2T1[,2],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(theta[1]),main="", cex.lab = 1.5)
points(density(resultsA2T2[,2],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA2T3[,2],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA2[2],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))

plot(density(resultsA2T1[,3],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(gamma),main="", cex.lab = 1.5)
points(density(resultsA2T2[,3],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA2T3[,3],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA2[3],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))
```





## Scenario 3



$\alpha=0.7$,\
$\lambda_+=1$,\
$\lambda_-=0.5$,\

### Simulation with my codes

```{r}
tablaA3T1<-apply(resultsA3T1,2,mean.sd)
tablaA3T2<-apply(resultsA3T2,2,mean.sd)
tablaA3T3<-apply(resultsA3T3,2,mean.sd)
tablaA3<-rbind(tablaA3T1,tablaA3T2,tablaA3T3)
row.names(tablaA3)<-c("T1.mean","sd","T2.mean","sd","T3mean","sd")
round(tablaA3,4)
parametrosA3
```


```{r}
tablaA3T1<-apply(resultsA3T1,2,kurtosis.skewness)
tablaA3T2<-apply(resultsA3T2,2,kurtosis.skewness)
tablaA3T3<-apply(resultsA3T3,2,kurtosis.skewness)
rownames(tablaA3T1)<-c("kurtosis","skewness")
rownames(tablaA3T2)<-c("kurtosis","skewness")
rownames(tablaA3T3)<-c("kurtosis","skewness")
tablaA3<-rbind(tablaA3T1,tablaA3T2,tablaA3T3)
round(tablaA3,4)
```

Density estimates 

```{r,fig.width=10, fig.height=3}
par(mfrow=c(1,3))
plot(density(resultsA3T1[,1],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(theta[0]),main="", cex.lab = 1.5)
points(density(resultsA3T2[,1],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA3T3[,1],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA3[1],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))

plot(density(resultsA3T1[,2],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(theta[1]),main="", cex.lab = 1.5)
points(density(resultsA3T2[,2],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA3T3[,2],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA3[2],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))

plot(density(resultsA3T1[,3],adjust = 1.5),lty=1,col=2,ylim=c(0,5),xlab=expression(gamma),main="", cex.lab = 1.5)
points(density(resultsA3T2[,3],adjust = 1.5),type="l",lty=4,col=3)
points(density(resultsA3T3[,3],adjust = 1.5),type="l",lty=5,col=4)
abline(v=parametrosA3[3],col=6)
legend("topright",c("T=500","T=1000","T=1500"),lty=c(1,4,5),col=c(2,3,4))
```




